/*
 * This file is generated by jOOQ.
 */
package example.app.domain.user.infrastructure.data.schema.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserPassword implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long   userId;
    private String password;

    public UserPassword() {}

    public UserPassword(UserPassword value) {
        this.userId = value.userId;
        this.password = value.password;
    }

    public UserPassword(
        Long   userId,
        String password
    ) {
        this.userId = userId;
        this.password = password;
    }

    /**
     * Getter for <code>test.user_password.user_id</code>.
     */
    public Long getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>test.user_password.user_id</code>.
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * Getter for <code>test.user_password.password</code>.
     */
    public String getPassword() {
        return this.password;
    }

    /**
     * Setter for <code>test.user_password.password</code>.
     */
    public void setPassword(String password) {
        this.password = password;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserPassword (");

        sb.append(userId);
        sb.append(", ").append(password);

        sb.append(")");
        return sb.toString();
    }
}
