/*
 * This file is generated by jOOQ.
 */
package example.app.domain.social.infrastructure.data.schema;


import example.app.domain.social.infrastructure.data.schema.tables.Article;
import example.app.domain.social.infrastructure.data.schema.tables.ArticleFavorite;
import example.app.domain.social.infrastructure.data.schema.tables.ArticleReply;
import example.app.domain.social.infrastructure.data.schema.tables.ArticleStar;
import example.app.domain.social.infrastructure.data.schema.tables.Poster;
import example.app.domain.social.infrastructure.data.schema.tables.PosterFollow;


/**
 * Convenience access to all tables in test.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>test.article</code>.
     */
    public static final Article ARTICLE = Article.ARTICLE;

    /**
     * The table <code>test.article_favorite</code>.
     */
    public static final ArticleFavorite ARTICLE_FAVORITE = ArticleFavorite.ARTICLE_FAVORITE;

    /**
     * The table <code>test.article_reply</code>.
     */
    public static final ArticleReply ARTICLE_REPLY = ArticleReply.ARTICLE_REPLY;

    /**
     * The table <code>test.article_star</code>.
     */
    public static final ArticleStar ARTICLE_STAR = ArticleStar.ARTICLE_STAR;

    /**
     * The table <code>test.poster</code>.
     */
    public static final Poster POSTER = Poster.POSTER;

    /**
     * The table <code>test.poster_follow</code>.
     */
    public static final PosterFollow POSTER_FOLLOW = PosterFollow.POSTER_FOLLOW;
}
