/*
 * This file is generated by jOOQ.
 */
package example.app.domain.social.infrastructure.data.schema;


import example.app.domain.social.infrastructure.data.schema.tables.Article;
import example.app.domain.social.infrastructure.data.schema.tables.ArticleFavorite;
import example.app.domain.social.infrastructure.data.schema.tables.ArticleReply;
import example.app.domain.social.infrastructure.data.schema.tables.ArticleStar;
import example.app.domain.social.infrastructure.data.schema.tables.Poster;
import example.app.domain.social.infrastructure.data.schema.tables.PosterFollow;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Test extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>test</code>
     */
    public static final Test TEST = new Test();

    /**
     * The table <code>test.article</code>.
     */
    public final Article ARTICLE = Article.ARTICLE;

    /**
     * The table <code>test.article_favorite</code>.
     */
    public final ArticleFavorite ARTICLE_FAVORITE = ArticleFavorite.ARTICLE_FAVORITE;

    /**
     * The table <code>test.article_reply</code>.
     */
    public final ArticleReply ARTICLE_REPLY = ArticleReply.ARTICLE_REPLY;

    /**
     * The table <code>test.article_star</code>.
     */
    public final ArticleStar ARTICLE_STAR = ArticleStar.ARTICLE_STAR;

    /**
     * The table <code>test.poster</code>.
     */
    public final Poster POSTER = Poster.POSTER;

    /**
     * The table <code>test.poster_follow</code>.
     */
    public final PosterFollow POSTER_FOLLOW = PosterFollow.POSTER_FOLLOW;

    /**
     * No further instances allowed
     */
    private Test() {
        super("test", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Article.ARTICLE,
            ArticleFavorite.ARTICLE_FAVORITE,
            ArticleReply.ARTICLE_REPLY,
            ArticleStar.ARTICLE_STAR,
            Poster.POSTER,
            PosterFollow.POSTER_FOLLOW);
    }
}
