/*
 * This file is generated by jOOQ.
 */
package example.social.domain.user.infrastructure.data.schema;


import example.social.domain.user.infrastructure.data.schema.tables.User;
import example.social.domain.user.infrastructure.data.schema.tables.UserPassword;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Test extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>test</code>
     */
    public static final Test TEST = new Test();

    /**
     * The table <code>test.user</code>.
     */
    public final User USER = User.USER;

    /**
     * The table <code>test.user_password</code>.
     */
    public final UserPassword USER_PASSWORD = UserPassword.USER_PASSWORD;

    /**
     * No further instances allowed
     */
    private Test() {
        super("test", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            User.USER,
            UserPassword.USER_PASSWORD);
    }
}
