/*
 * This file is generated by jOOQ.
 */
package example.app.domain.social.infrastructure.data.schema.tables;


import example.app.domain.social.infrastructure.data.schema.Keys;
import example.app.domain.social.infrastructure.data.schema.Test;
import example.app.domain.social.infrastructure.data.schema.tables.records.ArticleFavoriteRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ArticleFavorite extends TableImpl<ArticleFavoriteRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>test.article_favorite</code>
     */
    public static final ArticleFavorite ARTICLE_FAVORITE = new ArticleFavorite();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ArticleFavoriteRecord> getRecordType() {
        return ArticleFavoriteRecord.class;
    }

    /**
     * The column <code>test.article_favorite.article_id</code>. the article id
     */
    public final TableField<ArticleFavoriteRecord, Long> ARTICLE_ID = createField(DSL.name("article_id"), SQLDataType.BIGINT.nullable(false), this, "the article id");

    /**
     * The column <code>test.article_favorite.favorited_by</code>. the poster id who favorited the article
     */
    public final TableField<ArticleFavoriteRecord, Long> FAVORITED_BY = createField(DSL.name("favorited_by"), SQLDataType.BIGINT.nullable(false), this, "the poster id who favorited the article");

    /**
     * The column <code>test.article_favorite.favorited_at</code>. the favorited time
     */
    public final TableField<ArticleFavoriteRecord, Long> FAVORITED_AT = createField(DSL.name("favorited_at"), SQLDataType.BIGINT.nullable(false), this, "the favorited time");

    private ArticleFavorite(Name alias, Table<ArticleFavoriteRecord> aliased) {
        this(alias, aliased, null);
    }

    private ArticleFavorite(Name alias, Table<ArticleFavoriteRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>test.article_favorite</code> table reference
     */
    public ArticleFavorite(String alias) {
        this(DSL.name(alias), ARTICLE_FAVORITE);
    }

    /**
     * Create an aliased <code>test.article_favorite</code> table reference
     */
    public ArticleFavorite(Name alias) {
        this(alias, ARTICLE_FAVORITE);
    }

    /**
     * Create a <code>test.article_favorite</code> table reference
     */
    public ArticleFavorite() {
        this(DSL.name("article_favorite"), null);
    }

    public <O extends Record> ArticleFavorite(Table<O> child, ForeignKey<O, ArticleFavoriteRecord> key) {
        super(child, key, ARTICLE_FAVORITE);
    }

    @Override
    public Schema getSchema() {
        return Test.TEST;
    }

    @Override
    public UniqueKey<ArticleFavoriteRecord> getPrimaryKey() {
        return Keys.KEY_ARTICLE_FAVORITE_PRIMARY;
    }

    @Override
    public List<UniqueKey<ArticleFavoriteRecord>> getKeys() {
        return Arrays.<UniqueKey<ArticleFavoriteRecord>>asList(Keys.KEY_ARTICLE_FAVORITE_PRIMARY);
    }

    @Override
    public List<ForeignKey<ArticleFavoriteRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ArticleFavoriteRecord, ?>>asList(Keys.ARTICLE_FAVORITE_FK, Keys.ARTICLE_FAVORITE_FK_1);
    }

    private transient Article _article;
    private transient Poster _poster;

    public Article article() {
        if (_article == null)
            _article = new Article(this, Keys.ARTICLE_FAVORITE_FK);

        return _article;
    }

    public Poster poster() {
        if (_poster == null)
            _poster = new Poster(this, Keys.ARTICLE_FAVORITE_FK_1);

        return _poster;
    }

    @Override
    public ArticleFavorite as(String alias) {
        return new ArticleFavorite(DSL.name(alias), this);
    }

    @Override
    public ArticleFavorite as(Name alias) {
        return new ArticleFavorite(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ArticleFavorite rename(String name) {
        return new ArticleFavorite(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ArticleFavorite rename(Name name) {
        return new ArticleFavorite(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, Long, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
