/*
 * This file is generated by jOOQ.
 */
package example.app.domain.social.infrastructure.data.schema.tables;


import example.app.domain.social.infrastructure.data.schema.Keys;
import example.app.domain.social.infrastructure.data.schema.Test;
import example.app.domain.social.infrastructure.data.schema.tables.records.ArticleStarRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ArticleStar extends TableImpl<ArticleStarRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>test.article_star</code>
     */
    public static final ArticleStar ARTICLE_STAR = new ArticleStar();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ArticleStarRecord> getRecordType() {
        return ArticleStarRecord.class;
    }

    /**
     * The column <code>test.article_star.article_id</code>. the article id
     */
    public final TableField<ArticleStarRecord, Long> ARTICLE_ID = createField(DSL.name("article_id"), SQLDataType.BIGINT.nullable(false), this, "the article id");

    /**
     * The column <code>test.article_star.stared_by</code>. the poster id who stared the article
     */
    public final TableField<ArticleStarRecord, Long> STARED_BY = createField(DSL.name("stared_by"), SQLDataType.BIGINT.nullable(false), this, "the poster id who stared the article");

    /**
     * The column <code>test.article_star.stared_at</code>. the stared time
     */
    public final TableField<ArticleStarRecord, Long> STARED_AT = createField(DSL.name("stared_at"), SQLDataType.BIGINT.nullable(false), this, "the stared time");

    private ArticleStar(Name alias, Table<ArticleStarRecord> aliased) {
        this(alias, aliased, null);
    }

    private ArticleStar(Name alias, Table<ArticleStarRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>test.article_star</code> table reference
     */
    public ArticleStar(String alias) {
        this(DSL.name(alias), ARTICLE_STAR);
    }

    /**
     * Create an aliased <code>test.article_star</code> table reference
     */
    public ArticleStar(Name alias) {
        this(alias, ARTICLE_STAR);
    }

    /**
     * Create a <code>test.article_star</code> table reference
     */
    public ArticleStar() {
        this(DSL.name("article_star"), null);
    }

    public <O extends Record> ArticleStar(Table<O> child, ForeignKey<O, ArticleStarRecord> key) {
        super(child, key, ARTICLE_STAR);
    }

    @Override
    public Schema getSchema() {
        return Test.TEST;
    }

    @Override
    public UniqueKey<ArticleStarRecord> getPrimaryKey() {
        return Keys.KEY_ARTICLE_STAR_PRIMARY;
    }

    @Override
    public List<UniqueKey<ArticleStarRecord>> getKeys() {
        return Arrays.<UniqueKey<ArticleStarRecord>>asList(Keys.KEY_ARTICLE_STAR_PRIMARY);
    }

    @Override
    public List<ForeignKey<ArticleStarRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ArticleStarRecord, ?>>asList(Keys.ARTICLE_STAR_FK, Keys.ARTICLE_STAR_FK_1);
    }

    private transient Article _article;
    private transient Poster _poster;

    public Article article() {
        if (_article == null)
            _article = new Article(this, Keys.ARTICLE_STAR_FK);

        return _article;
    }

    public Poster poster() {
        if (_poster == null)
            _poster = new Poster(this, Keys.ARTICLE_STAR_FK_1);

        return _poster;
    }

    @Override
    public ArticleStar as(String alias) {
        return new ArticleStar(DSL.name(alias), this);
    }

    @Override
    public ArticleStar as(Name alias) {
        return new ArticleStar(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ArticleStar rename(String name) {
        return new ArticleStar(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ArticleStar rename(Name name) {
        return new ArticleStar(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, Long, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
