/*
 * This file is generated by jOOQ.
 */
package example.app.domain.social.infrastructure.data.schema.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Article implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long   id;
    private Long   posterId;
    private String content;
    private Long   postedAt;
    private Long   updatedAt;
    private Long   sharingArticleId;

    public Article() {}

    public Article(Article value) {
        this.id = value.id;
        this.posterId = value.posterId;
        this.content = value.content;
        this.postedAt = value.postedAt;
        this.updatedAt = value.updatedAt;
        this.sharingArticleId = value.sharingArticleId;
    }

    public Article(
        Long   id,
        Long   posterId,
        String content,
        Long   postedAt,
        Long   updatedAt,
        Long   sharingArticleId
    ) {
        this.id = id;
        this.posterId = posterId;
        this.content = content;
        this.postedAt = postedAt;
        this.updatedAt = updatedAt;
        this.sharingArticleId = sharingArticleId;
    }

    /**
     * Getter for <code>test.article.id</code>. id
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>test.article.id</code>. id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>test.article.poster_id</code>. the poster id who posted this article
     */
    public Long getPosterId() {
        return this.posterId;
    }

    /**
     * Setter for <code>test.article.poster_id</code>. the poster id who posted this article
     */
    public void setPosterId(Long posterId) {
        this.posterId = posterId;
    }

    /**
     * Getter for <code>test.article.content</code>. the posted content
     */
    public String getContent() {
        return this.content;
    }

    /**
     * Setter for <code>test.article.content</code>. the posted content
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * Getter for <code>test.article.posted_at</code>. the posted time
     */
    public Long getPostedAt() {
        return this.postedAt;
    }

    /**
     * Setter for <code>test.article.posted_at</code>. the posted time
     */
    public void setPostedAt(Long postedAt) {
        this.postedAt = postedAt;
    }

    /**
     * Getter for <code>test.article.updated_at</code>. the last update time
     */
    public Long getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>test.article.updated_at</code>. the last update time
     */
    public void setUpdatedAt(Long updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>test.article.sharing_article_id</code>. the article id shared by this article, may be null, means this article did not share any article
     */
    public Long getSharingArticleId() {
        return this.sharingArticleId;
    }

    /**
     * Setter for <code>test.article.sharing_article_id</code>. the article id shared by this article, may be null, means this article did not share any article
     */
    public void setSharingArticleId(Long sharingArticleId) {
        this.sharingArticleId = sharingArticleId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Article (");

        sb.append(id);
        sb.append(", ").append(posterId);
        sb.append(", ").append(content);
        sb.append(", ").append(postedAt);
        sb.append(", ").append(updatedAt);
        sb.append(", ").append(sharingArticleId);

        sb.append(")");
        return sb.toString();
    }
}
