/*
 * This file is generated by jOOQ.
 */
package example.app.domain.social.infrastructure.data.schema.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ArticleFavorite implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long articleId;
    private Long favoritedBy;
    private Long favoritedAt;

    public ArticleFavorite() {}

    public ArticleFavorite(ArticleFavorite value) {
        this.articleId = value.articleId;
        this.favoritedBy = value.favoritedBy;
        this.favoritedAt = value.favoritedAt;
    }

    public ArticleFavorite(
        Long articleId,
        Long favoritedBy,
        Long favoritedAt
    ) {
        this.articleId = articleId;
        this.favoritedBy = favoritedBy;
        this.favoritedAt = favoritedAt;
    }

    /**
     * Getter for <code>test.article_favorite.article_id</code>. the article id
     */
    public Long getArticleId() {
        return this.articleId;
    }

    /**
     * Setter for <code>test.article_favorite.article_id</code>. the article id
     */
    public void setArticleId(Long articleId) {
        this.articleId = articleId;
    }

    /**
     * Getter for <code>test.article_favorite.favorited_by</code>. the poster id who favorited the article
     */
    public Long getFavoritedBy() {
        return this.favoritedBy;
    }

    /**
     * Setter for <code>test.article_favorite.favorited_by</code>. the poster id who favorited the article
     */
    public void setFavoritedBy(Long favoritedBy) {
        this.favoritedBy = favoritedBy;
    }

    /**
     * Getter for <code>test.article_favorite.favorited_at</code>. the favorited time
     */
    public Long getFavoritedAt() {
        return this.favoritedAt;
    }

    /**
     * Setter for <code>test.article_favorite.favorited_at</code>. the favorited time
     */
    public void setFavoritedAt(Long favoritedAt) {
        this.favoritedAt = favoritedAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ArticleFavorite (");

        sb.append(articleId);
        sb.append(", ").append(favoritedBy);
        sb.append(", ").append(favoritedAt);

        sb.append(")");
        return sb.toString();
    }
}
