/*
 * This file is generated by jOOQ.
 */
package example.app.domain.social.infrastructure.data.schema.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ArticleStar implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long articleId;
    private Long staredBy;
    private Long staredAt;

    public ArticleStar() {}

    public ArticleStar(ArticleStar value) {
        this.articleId = value.articleId;
        this.staredBy = value.staredBy;
        this.staredAt = value.staredAt;
    }

    public ArticleStar(
        Long articleId,
        Long staredBy,
        Long staredAt
    ) {
        this.articleId = articleId;
        this.staredBy = staredBy;
        this.staredAt = staredAt;
    }

    /**
     * Getter for <code>test.article_star.article_id</code>. the article id
     */
    public Long getArticleId() {
        return this.articleId;
    }

    /**
     * Setter for <code>test.article_star.article_id</code>. the article id
     */
    public void setArticleId(Long articleId) {
        this.articleId = articleId;
    }

    /**
     * Getter for <code>test.article_star.stared_by</code>. the poster id who stared the article
     */
    public Long getStaredBy() {
        return this.staredBy;
    }

    /**
     * Setter for <code>test.article_star.stared_by</code>. the poster id who stared the article
     */
    public void setStaredBy(Long staredBy) {
        this.staredBy = staredBy;
    }

    /**
     * Getter for <code>test.article_star.stared_at</code>. the stared time
     */
    public Long getStaredAt() {
        return this.staredAt;
    }

    /**
     * Setter for <code>test.article_star.stared_at</code>. the stared time
     */
    public void setStaredAt(Long staredAt) {
        this.staredAt = staredAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ArticleStar (");

        sb.append(articleId);
        sb.append(", ").append(staredBy);
        sb.append(", ").append(staredAt);

        sb.append(")");
        return sb.toString();
    }
}
