/*
 * This file is generated by jOOQ.
 */
package example.app.domain.social.infrastructure.data.schema.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ArticleReply implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long   id;
    private Long   articleId;
    private String content;
    private Long   repliedBy;
    private Long   repliedAt;

    public ArticleReply() {}

    public ArticleReply(ArticleReply value) {
        this.id = value.id;
        this.articleId = value.articleId;
        this.content = value.content;
        this.repliedBy = value.repliedBy;
        this.repliedAt = value.repliedAt;
    }

    public ArticleReply(
        Long   id,
        Long   articleId,
        String content,
        Long   repliedBy,
        Long   repliedAt
    ) {
        this.id = id;
        this.articleId = articleId;
        this.content = content;
        this.repliedBy = repliedBy;
        this.repliedAt = repliedAt;
    }

    /**
     * Getter for <code>test.article_reply.id</code>. id
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>test.article_reply.id</code>. id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>test.article_reply.article_id</code>. the article id which this reply replied to
     */
    public Long getArticleId() {
        return this.articleId;
    }

    /**
     * Setter for <code>test.article_reply.article_id</code>. the article id which this reply replied to
     */
    public void setArticleId(Long articleId) {
        this.articleId = articleId;
    }

    /**
     * Getter for <code>test.article_reply.content</code>. the replied content
     */
    public String getContent() {
        return this.content;
    }

    /**
     * Setter for <code>test.article_reply.content</code>. the replied content
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * Getter for <code>test.article_reply.replied_by</code>. the poster id who replied the article
     */
    public Long getRepliedBy() {
        return this.repliedBy;
    }

    /**
     * Setter for <code>test.article_reply.replied_by</code>. the poster id who replied the article
     */
    public void setRepliedBy(Long repliedBy) {
        this.repliedBy = repliedBy;
    }

    /**
     * Getter for <code>test.article_reply.replied_at</code>. the replied time
     */
    public Long getRepliedAt() {
        return this.repliedAt;
    }

    /**
     * Setter for <code>test.article_reply.replied_at</code>. the replied time
     */
    public void setRepliedAt(Long repliedAt) {
        this.repliedAt = repliedAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ArticleReply (");

        sb.append(id);
        sb.append(", ").append(articleId);
        sb.append(", ").append(content);
        sb.append(", ").append(repliedBy);
        sb.append(", ").append(repliedAt);

        sb.append(")");
        return sb.toString();
    }
}
