/*
 * This file is generated by jOOQ.
 */
package example.app.domain.social.infrastructure.data.schema.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Poster implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long   id;
    private String name;
    private String account;
    private Long   deletedAt;

    public Poster() {}

    public Poster(Poster value) {
        this.id = value.id;
        this.name = value.name;
        this.account = value.account;
        this.deletedAt = value.deletedAt;
    }

    public Poster(
        Long   id,
        String name,
        String account,
        Long   deletedAt
    ) {
        this.id = id;
        this.name = name;
        this.account = account;
        this.deletedAt = deletedAt;
    }

    /**
     * Getter for <code>test.poster.id</code>. id
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>test.poster.id</code>. id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>test.poster.name</code>. poster name
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>test.poster.name</code>. poster name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>test.poster.account</code>. poster account
     */
    public String getAccount() {
        return this.account;
    }

    /**
     * Setter for <code>test.poster.account</code>. poster account
     */
    public void setAccount(String account) {
        this.account = account;
    }

    /**
     * Getter for <code>test.poster.deleted_at</code>. the time when the poster was deleted, may be null, means the poster not been deleted yet.
     */
    public Long getDeletedAt() {
        return this.deletedAt;
    }

    /**
     * Setter for <code>test.poster.deleted_at</code>. the time when the poster was deleted, may be null, means the poster not been deleted yet.
     */
    public void setDeletedAt(Long deletedAt) {
        this.deletedAt = deletedAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Poster (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(account);
        sb.append(", ").append(deletedAt);

        sb.append(")");
        return sb.toString();
    }
}
