/*
 * This file is generated by jOOQ.
 */
package example.app.domain.social.infrastructure.data.schema.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PosterFollow implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long posterId;
    private Long followedBy;
    private Long followedAt;

    public PosterFollow() {}

    public PosterFollow(PosterFollow value) {
        this.posterId = value.posterId;
        this.followedBy = value.followedBy;
        this.followedAt = value.followedAt;
    }

    public PosterFollow(
        Long posterId,
        Long followedBy,
        Long followedAt
    ) {
        this.posterId = posterId;
        this.followedBy = followedBy;
        this.followedAt = followedAt;
    }

    /**
     * Getter for <code>test.poster_follow.poster_id</code>. the poster id who was been followed
     */
    public Long getPosterId() {
        return this.posterId;
    }

    /**
     * Setter for <code>test.poster_follow.poster_id</code>. the poster id who was been followed
     */
    public void setPosterId(Long posterId) {
        this.posterId = posterId;
    }

    /**
     * Getter for <code>test.poster_follow.followed_by</code>. the poster id of the follower
     */
    public Long getFollowedBy() {
        return this.followedBy;
    }

    /**
     * Setter for <code>test.poster_follow.followed_by</code>. the poster id of the follower
     */
    public void setFollowedBy(Long followedBy) {
        this.followedBy = followedBy;
    }

    /**
     * Getter for <code>test.poster_follow.followed_at</code>. the followed time
     */
    public Long getFollowedAt() {
        return this.followedAt;
    }

    /**
     * Setter for <code>test.poster_follow.followed_at</code>. the followed time
     */
    public void setFollowedAt(Long followedAt) {
        this.followedAt = followedAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PosterFollow (");

        sb.append(posterId);
        sb.append(", ").append(followedBy);
        sb.append(", ").append(followedAt);

        sb.append(")");
        return sb.toString();
    }
}
