/*
 * This file is generated by jOOQ.
 */
package example.app.domain.social.infrastructure.data.schema.tables.records;


import example.app.domain.social.infrastructure.data.schema.tables.ArticleFavorite;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ArticleFavoriteRecord extends UpdatableRecordImpl<ArticleFavoriteRecord> implements Record3<Long, Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>test.article_favorite.article_id</code>. the article id
     */
    public void setArticleId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>test.article_favorite.article_id</code>. the article id
     */
    public Long getArticleId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>test.article_favorite.favorited_by</code>. the poster id who favorited the article
     */
    public void setFavoritedBy(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>test.article_favorite.favorited_by</code>. the poster id who favorited the article
     */
    public Long getFavoritedBy() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>test.article_favorite.favorited_at</code>. the favorited time
     */
    public void setFavoritedAt(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>test.article_favorite.favorited_at</code>. the favorited time
     */
    public Long getFavoritedAt() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, Long, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Long, Long, Long> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return ArticleFavorite.ARTICLE_FAVORITE.ARTICLE_ID;
    }

    @Override
    public Field<Long> field2() {
        return ArticleFavorite.ARTICLE_FAVORITE.FAVORITED_BY;
    }

    @Override
    public Field<Long> field3() {
        return ArticleFavorite.ARTICLE_FAVORITE.FAVORITED_AT;
    }

    @Override
    public Long component1() {
        return getArticleId();
    }

    @Override
    public Long component2() {
        return getFavoritedBy();
    }

    @Override
    public Long component3() {
        return getFavoritedAt();
    }

    @Override
    public Long value1() {
        return getArticleId();
    }

    @Override
    public Long value2() {
        return getFavoritedBy();
    }

    @Override
    public Long value3() {
        return getFavoritedAt();
    }

    @Override
    public ArticleFavoriteRecord value1(Long value) {
        setArticleId(value);
        return this;
    }

    @Override
    public ArticleFavoriteRecord value2(Long value) {
        setFavoritedBy(value);
        return this;
    }

    @Override
    public ArticleFavoriteRecord value3(Long value) {
        setFavoritedAt(value);
        return this;
    }

    @Override
    public ArticleFavoriteRecord values(Long value1, Long value2, Long value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ArticleFavoriteRecord
     */
    public ArticleFavoriteRecord() {
        super(ArticleFavorite.ARTICLE_FAVORITE);
    }

    /**
     * Create a detached, initialised ArticleFavoriteRecord
     */
    public ArticleFavoriteRecord(Long articleId, Long favoritedBy, Long favoritedAt) {
        super(ArticleFavorite.ARTICLE_FAVORITE);

        setArticleId(articleId);
        setFavoritedBy(favoritedBy);
        setFavoritedAt(favoritedAt);
    }
}
