/*
 * This file is generated by jOOQ.
 */
package example.app.domain.social.infrastructure.data.schema.tables.records;


import example.app.domain.social.infrastructure.data.schema.tables.ArticleReply;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ArticleReplyRecord extends UpdatableRecordImpl<ArticleReplyRecord> implements Record5<Long, Long, String, Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>test.article_reply.id</code>. id
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>test.article_reply.id</code>. id
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>test.article_reply.article_id</code>. the article id which this reply replied to
     */
    public void setArticleId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>test.article_reply.article_id</code>. the article id which this reply replied to
     */
    public Long getArticleId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>test.article_reply.content</code>. the replied content
     */
    public void setContent(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>test.article_reply.content</code>. the replied content
     */
    public String getContent() {
        return (String) get(2);
    }

    /**
     * Setter for <code>test.article_reply.replied_by</code>. the poster id who replied the article
     */
    public void setRepliedBy(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>test.article_reply.replied_by</code>. the poster id who replied the article
     */
    public Long getRepliedBy() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>test.article_reply.replied_at</code>. the replied time
     */
    public void setRepliedAt(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>test.article_reply.replied_at</code>. the replied time
     */
    public Long getRepliedAt() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, Long, String, Long, Long> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, Long, String, Long, Long> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return ArticleReply.ARTICLE_REPLY.ID;
    }

    @Override
    public Field<Long> field2() {
        return ArticleReply.ARTICLE_REPLY.ARTICLE_ID;
    }

    @Override
    public Field<String> field3() {
        return ArticleReply.ARTICLE_REPLY.CONTENT;
    }

    @Override
    public Field<Long> field4() {
        return ArticleReply.ARTICLE_REPLY.REPLIED_BY;
    }

    @Override
    public Field<Long> field5() {
        return ArticleReply.ARTICLE_REPLY.REPLIED_AT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getArticleId();
    }

    @Override
    public String component3() {
        return getContent();
    }

    @Override
    public Long component4() {
        return getRepliedBy();
    }

    @Override
    public Long component5() {
        return getRepliedAt();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getArticleId();
    }

    @Override
    public String value3() {
        return getContent();
    }

    @Override
    public Long value4() {
        return getRepliedBy();
    }

    @Override
    public Long value5() {
        return getRepliedAt();
    }

    @Override
    public ArticleReplyRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public ArticleReplyRecord value2(Long value) {
        setArticleId(value);
        return this;
    }

    @Override
    public ArticleReplyRecord value3(String value) {
        setContent(value);
        return this;
    }

    @Override
    public ArticleReplyRecord value4(Long value) {
        setRepliedBy(value);
        return this;
    }

    @Override
    public ArticleReplyRecord value5(Long value) {
        setRepliedAt(value);
        return this;
    }

    @Override
    public ArticleReplyRecord values(Long value1, Long value2, String value3, Long value4, Long value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ArticleReplyRecord
     */
    public ArticleReplyRecord() {
        super(ArticleReply.ARTICLE_REPLY);
    }

    /**
     * Create a detached, initialised ArticleReplyRecord
     */
    public ArticleReplyRecord(Long id, Long articleId, String content, Long repliedBy, Long repliedAt) {
        super(ArticleReply.ARTICLE_REPLY);

        setId(id);
        setArticleId(articleId);
        setContent(content);
        setRepliedBy(repliedBy);
        setRepliedAt(repliedAt);
    }
}
