/*
 * This file is generated by jOOQ.
 */
package example.app.domain.social.infrastructure.data.schema.tables.records;


import example.app.domain.social.infrastructure.data.schema.tables.ArticleStar;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ArticleStarRecord extends UpdatableRecordImpl<ArticleStarRecord> implements Record3<Long, Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>test.article_star.article_id</code>. the article id
     */
    public void setArticleId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>test.article_star.article_id</code>. the article id
     */
    public Long getArticleId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>test.article_star.stared_by</code>. the poster id who stared the article
     */
    public void setStaredBy(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>test.article_star.stared_by</code>. the poster id who stared the article
     */
    public Long getStaredBy() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>test.article_star.stared_at</code>. the stared time
     */
    public void setStaredAt(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>test.article_star.stared_at</code>. the stared time
     */
    public Long getStaredAt() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, Long, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Long, Long, Long> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return ArticleStar.ARTICLE_STAR.ARTICLE_ID;
    }

    @Override
    public Field<Long> field2() {
        return ArticleStar.ARTICLE_STAR.STARED_BY;
    }

    @Override
    public Field<Long> field3() {
        return ArticleStar.ARTICLE_STAR.STARED_AT;
    }

    @Override
    public Long component1() {
        return getArticleId();
    }

    @Override
    public Long component2() {
        return getStaredBy();
    }

    @Override
    public Long component3() {
        return getStaredAt();
    }

    @Override
    public Long value1() {
        return getArticleId();
    }

    @Override
    public Long value2() {
        return getStaredBy();
    }

    @Override
    public Long value3() {
        return getStaredAt();
    }

    @Override
    public ArticleStarRecord value1(Long value) {
        setArticleId(value);
        return this;
    }

    @Override
    public ArticleStarRecord value2(Long value) {
        setStaredBy(value);
        return this;
    }

    @Override
    public ArticleStarRecord value3(Long value) {
        setStaredAt(value);
        return this;
    }

    @Override
    public ArticleStarRecord values(Long value1, Long value2, Long value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ArticleStarRecord
     */
    public ArticleStarRecord() {
        super(ArticleStar.ARTICLE_STAR);
    }

    /**
     * Create a detached, initialised ArticleStarRecord
     */
    public ArticleStarRecord(Long articleId, Long staredBy, Long staredAt) {
        super(ArticleStar.ARTICLE_STAR);

        setArticleId(articleId);
        setStaredBy(staredBy);
        setStaredAt(staredAt);
    }
}
