/*
 * This file is generated by jOOQ.
 */
package example.app.domain.user.infrastructure.data.schema;


import example.app.domain.user.infrastructure.data.schema.tables.User;
import example.app.domain.user.infrastructure.data.schema.tables.UserPassword;


/**
 * Convenience access to all tables in test.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>test.user</code>.
     */
    public static final User USER = User.USER;

    /**
     * The table <code>test.user_password</code>.
     */
    public static final UserPassword USER_PASSWORD = UserPassword.USER_PASSWORD;
}
