/*
 * This file is generated by jOOQ.
 */
package example.app.domain.social.infrastructure.data.schema.tables.daos;


import example.app.domain.social.infrastructure.data.schema.tables.ArticleStar;
import example.app.domain.social.infrastructure.data.schema.tables.records.ArticleStarRecord;

import java.util.List;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ArticleStarDao extends DAOImpl<ArticleStarRecord, example.app.domain.social.infrastructure.data.schema.tables.pojos.ArticleStar, Record2<Long, Long>> {

    /**
     * Create a new ArticleStarDao without any configuration
     */
    public ArticleStarDao() {
        super(ArticleStar.ARTICLE_STAR, example.app.domain.social.infrastructure.data.schema.tables.pojos.ArticleStar.class);
    }

    /**
     * Create a new ArticleStarDao with an attached configuration
     */
    public ArticleStarDao(Configuration configuration) {
        super(ArticleStar.ARTICLE_STAR, example.app.domain.social.infrastructure.data.schema.tables.pojos.ArticleStar.class, configuration);
    }

    @Override
    public Record2<Long, Long> getId(example.app.domain.social.infrastructure.data.schema.tables.pojos.ArticleStar object) {
        return compositeKeyRecord(object.getArticleId(), object.getStaredBy());
    }

    /**
     * Fetch records that have <code>article_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<example.app.domain.social.infrastructure.data.schema.tables.pojos.ArticleStar> fetchRangeOfArticleId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ArticleStar.ARTICLE_STAR.ARTICLE_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>article_id IN (values)</code>
     */
    public List<example.app.domain.social.infrastructure.data.schema.tables.pojos.ArticleStar> fetchByArticleId(Long... values) {
        return fetch(ArticleStar.ARTICLE_STAR.ARTICLE_ID, values);
    }

    /**
     * Fetch records that have <code>stared_by BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<example.app.domain.social.infrastructure.data.schema.tables.pojos.ArticleStar> fetchRangeOfStaredBy(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ArticleStar.ARTICLE_STAR.STARED_BY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>stared_by IN (values)</code>
     */
    public List<example.app.domain.social.infrastructure.data.schema.tables.pojos.ArticleStar> fetchByStaredBy(Long... values) {
        return fetch(ArticleStar.ARTICLE_STAR.STARED_BY, values);
    }

    /**
     * Fetch records that have <code>stared_at BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<example.app.domain.social.infrastructure.data.schema.tables.pojos.ArticleStar> fetchRangeOfStaredAt(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ArticleStar.ARTICLE_STAR.STARED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>stared_at IN (values)</code>
     */
    public List<example.app.domain.social.infrastructure.data.schema.tables.pojos.ArticleStar> fetchByStaredAt(Long... values) {
        return fetch(ArticleStar.ARTICLE_STAR.STARED_AT, values);
    }
}
